package com.thirfir.domain

const val BASE_URL = "https://portal.koreatech.ac.kr/ctt/bb/bulletin"


// ----------- HTML 태그 -----------
const val U = "u"
const val B = "b"
const val STRIKE = "strike"
const val I = "i"
const val STRONG = "strong"
const val INS = "ins"
const val DEL = "del"
const val EM = "em"
const val SPAN = "span"
const val P = "p"
const val A = "a"
const val IMG = "img"
const val TABLE = "table"
const val H3 = "h3"
const val DIV = "div"
const val TBODY = "tbody"
const val TR = "tr"
const val TD = "td"
const val BR = "br"
// --------------------------------

const val STYLE = "style"
const val COLOR = "color"
const val BACKGROUND = "background"
const val BACKGROUND_COLOR = "background-color"     // Text의 배경색
const val FONT_SIZE = "font-size"       // 뒤에 pt or px가 붙음 , pt = px * 0.75 <- 12pt = 16px <- 약 14dp로 치환? 대충 dp = pt * 1.15
const val FONT_WEIGHT = "font-weight"   // bold or 700???
const val BORDER_STYLE = "border-style"
const val TEXT_ALIGN = "text-align"
const val TEXT_DECORATION_LINE = "text-decoration-line"
const val ROWSPAN = "rowspan"
const val COLSPAN = "colspan"
const val MARGIN = "margin"
const val PADDING = "padding"
const val PADDING_LEFT = "padding-left"
const val PADDING_RIGHT = "padding-right"
const val PADDING_TOP = "padding-top"
const val PADDING_BOTTOM = "padding-bottom"

const val START = "start"
const val END = "end"
const val LEFT = "left"
const val RIGHT = "right"
const val JUSTIFY = "justify"
const val CENTER = "center"
const val UNDERLINE = "underline"
const val LINE_THROUGH = "line-through"     // strike
const val NONE = "none"
const val BOLD = "bold"
const val ITALIC = "italic"
const val SOLID = "solid"
const val NORMAL = "normal"

const val BLACK = "black"
const val BLUE = "blue"
const val CYAN = "cyan"
const val DARK_GRAY = "darkgray"
const val GRAY = "gray"
const val GREEN = "green"
const val LIGHT_GRAY = "lightgray"
const val MAGENTA = "magenta"
const val RED = "red"
const val YELLOW = "yellow"
const val WHITE = "white"
const val TRANSPARENT = "transparent"
